### ISSUE TITLE
Error on calender view (Add Favicon)

### ISSUE THREAD

**Issue by Alexander-Klee** [Solidarische-Raumnutzung/solidarische-raumnutzung#100]
when visiting the calender view the console logs the following error
Method parameter 'roomId': Failed to convert value of type 'java.lang.String' to required type 'long'; For input string: "favicon.ico"]

(might have been fixed by roomId)

**Comment by Alexander-Klee** [comment]
It indeed just disappeared at some point ...

**Comment by Alexander-Klee** [comment]
It still occours

**Comment by JFronny** [comment]
The cause is probably that we serve the calendar under `/{roomId}`, which gets matched for `/favicon.ico` (the request to which is generated by the browser automatically). Naturally, `faavicon.ico` is not a number, so this causes an exception.
